### ISSUE TITLE
Edit root at admin app

### ISSUE THREAD

**Issue by mymai91** [mymai91/bookshelf#2]
Root default when I created
`lotus g action admin book#dashboard`

root default

`get '/book', to: 'book#dashboard'`

I updated it into:

```
get '/dashboard', to: 'book#dashboard'
```

I open: localhost:2300/dashboard it not work

**Comment by joneslee85** [comment]
@mymai91 which URL that `admin` app mounted to?

What error do you get?

**Comment by runlevel5** [comment]
When you do that generation, the new action would be generated for `admin` application. Updating your admin app routes looks good. But please remember that you mount `admin` into `/admin` as of https://github.com/mymai91/bookshelf/blob/master/config/environment.rb#L9.

So you have to access it at `locahost:2300/admin/dashboard`

**Comment by mymai91** [comment]
:+1: It good to me. Thanks you
